export const signInTypes = {
  CHANGE_MODAL: 'CHANGE_MODAL',
  CHANGE_RESET: 'CHANGE_RESET',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  UPDATE_ERROR: 'UPDATE_ERROR',
  UPDATE_FORGOT_ERROR: 'UPDATE_FORGOT_ERROR',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_USERNAME: 'UPDATE_USERNAME'
}