export const infoTypes = {
    GET_ASSOCIATE_LIST: "GET_ASSOCIATE_LIST",
    GET_PROJECT_LIST: "GET_PROJECT_LIST",
    GET_RESOURCE_CM_LIST: "GET_RESOURCE_CM_LIST",
    GET_RESOURCE_DESIGN_LIST: "GET_RESOURCE_DESIGN_LIST",
    GET_RESOURCE_LIST: "GET_RESOURCE_LIST",
    GET_RESOURCE_MOBILITY_LIST: "GET_RESOURCE_MOBILITY_LIST",
    GET_RESOURCE_UI_LIST: "GET_RESOURCE_UI_LIST",
    UPDATE_ERROR: "UPDATE_ERROR",
    UPDATE_TABLE_TYPE: "UPDATE_TABLE_TYPE",
    UPDATE_VIEW_ROW: "UPDATE_VIEW_ROW",
}