export const infoTypes = {
    GET_PROJECT_LIST: "GET_PROJECT_LIST",
    GET_RESOURCE_LIST: "GET_RESOURCE_LIST",
    UPDATE_ERROR: "UPDATE_ERROR",
    UPDATE_TABLE_TYPE: "UPDATE_TABLE_TYPE",
    UPDATE_VIEW_ROW: "UPDATE_VIEW_ROW",
}