export const infoTypes = {
    GET_ASSOCIATE_LIST: "GET_ASSOCIATE_LIST",
    GET_CERTIFICATION_LIST: "GET_CERTIFICATION_LIST",
    GET_PROJECT_LIST: "GET_PROJECT_LIST",
    GET_PROJECT_NAME: "GET_PROJECT_NAME",
    GET_RESOURCE_LIST: "GET_RESOURCE_LIST",
    GET_SKILL_GROUPS: "GET_SKILL_GROUPS",
    UPDATE_ERROR: "UPDATE_ERROR",
    UPDATE_TABLE_TYPE: "UPDATE_TABLE_TYPE",
    UPDATE_VIEW_ROW: "UPDATE_VIEW_ROW",
}