export const addSkillsTypes = {
    ADD_CERTIFICATION: 'ADD_CERTIFICATION',
    ADD_RESUMES: 'ADD_RESUMES',
    CANCEL_RESOURCE: 'CANCEL_RESOURCE',
    FETCH_CERTIFICATIONS: 'FETCH_CERTIFICATIONS',
    FETCH_COMPETENCY_TAGGINGS: 'FETCH_COMPETENCY_TAGGINGS',
    FETCH_GRADES: 'FETCH_GRADES',
    FETCH_LOCATIONS: 'FETCH_LOCATIONS',
    REMOVE_CERTIFICATION: 'REMOVE_CERTIFICATION',
    REMOVE_RESUME: 'REMOVE_RESUME',
    SUBMIT_RESOURCE: 'SUBMIT_RESOURCE',
    TOGGLE_SKILL_GROUP: 'TOGGLE_SKILL_GROUP',
    UPDATE_CERTIFICATION_SEARCH: 'UPDATE_CERTIFICATION_SEARCH',
    UPDATE_RESOURCE: 'UPDATE_RESOURCE',
    UPDATE_RESOURCE_SKILLS: 'UPDATE_RESOURCE_SKILLS'
}