export const addSkillsTypes = {
    FETCH_GRADES: 'FETCH_GRADES',
    FETCH_LOCATIONS: 'FETCH_LOCATIONS',
    TOGGLE_SKILL_GROUP: 'TOGGLE_SKILL_GROUP',
    UPDATE_RESOURCE: 'UPDATE_RESOURCE',
    UPDATE_RESOURCE_SKILLS: 'UPDATE_RESOURCE_SKILLS'
}